project:
  type: website
  output-dir: docs

website:
  site-url: https://svalvaro.github.io/
  title: ""
  favicon: images/me_drawing.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - posts.qmd
    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/svalvaro/"
        target: "_blank"
      - icon: github
        href: "https://github.com/svalvaro"
        target: "_blank"
  page-footer:
    background: light
    left: Copyright 2023, Álvaro Sánchez
    right: Last updated 12-2023
format:
  html:
    theme:
     # dark: cyborg
      light: minty
    css: styles.css
    mainfont: Nunito
    toc: true

editor: source

